export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const RECIPE_REPOSITORY = Symbol('RECIPE_REPOSITORY');
export const POKEMON_REPOSITORY = Symbol('POKEMON_REPOSITORY');
export const SEASONING_ITEM_REPOSITORY = Symbol('SEASONING_ITEM_REPOSITORY');

